### ISSUE TITLE
Debe ser considerado año de nacimiento, no Edad

### ISSUE THREAD

**Issue by torgus** [aitormagan/autocitamadrid-robot#4]
Ejemplo, ahora mismo, se pueden vacunar los nacidos en 1981, eso incluye gente de 39 o 40 años.

Si pones edad, 39 años, el sistema te dice que estas fuera, cuando en realidad, si has nacido en el 81, estas dentro .

**Comment by aitormagan** [comment]
Como bien dices, si tienes 39, pero este año cumples 40, ya puedes pedir cita para vacunarte. Quizás, en vez de pedir la edad, se puede pedir únicamente el año de nacimiento para evitar este tipo de problemas. Le echo un ojo. Gracias ;)
